using System;
using System.Collections.Generic;

namespace TubeLibrary
{
    public class StationReader : IReader
    {

        public Dictionary<string, HashSet<string>> GetStations()
        {
            var dict = new Dictionary<string, HashSet<string>>();
            var tuples = getTuples();

            foreach (var tup in tuples)
            {
                AddToDictionary(dict, tup.Item1, tup.Item2);
                AddToDictionary(dict, tup.Item2, tup.Item1);
            }
            return dict;
        }

        private void AddToDictionary(Dictionary<string, HashSet<string>> dict, string item1, string item2)
        {
            HashSet<string> hs = null;

            var success = dict.TryGetValue(item1, out hs);

            if (success)
            {
                hs.Add(item2);
            }
            else
            {
                dict.Add(item1, new HashSet<string> { item2 });
            }
        }

   

        private static IEnumerable<Tuple<string, string>> getTuples()
        {
            var tupleList = new List<Tuple<string, string>>();

            tupleList.Add(new Tuple<string, string>("Harrow and Wealdstone", "Kenton"));
            tupleList.Add(new Tuple<string, string>("Warwick Avenue", "Paddington"));
            tupleList.Add(new Tuple<string, string>("Edgware Road (Bakerloo)", "Marylebone"));
            tupleList.Add(new Tuple<string, string>("Marylebone", "Baker Street"));
            tupleList.Add(new Tuple<string, string>("Baker Street", "Regents Park"));
            tupleList.Add(new Tuple<string, string>("Regents Park", "Oxford Circus"));
            tupleList.Add(new Tuple<string, string>("Oxford Circus", "Piccadilly Circus"));
            tupleList.Add(new Tuple<string, string>("Piccadilly Circus", "Charing Cross"));
            tupleList.Add(new Tuple<string, string>("Charing Cross", "Embankment"));
            tupleList.Add(new Tuple<string, string>("Embankment", "Waterloo"));
            tupleList.Add(new Tuple<string, string>("Waterloo", "Lambeth North"));
            tupleList.Add(new Tuple<string, string>("Lambeth North", "Elephant and Castle"));
            tupleList.Add(new Tuple<string, string>("Maida Vale", "Warwick Avenue"));
            tupleList.Add(new Tuple<string, string>("Kilburn Park", "Maida Vale"));
            tupleList.Add(new Tuple<string, string>("Kenton", "South Kenton"));
            tupleList.Add(new Tuple<string, string>("South Kenton", "North Wembley"));
            tupleList.Add(new Tuple<string, string>("North Wembley", "Wembley Central"));
            tupleList.Add(new Tuple<string, string>("Wembley Central", "Stonebridge Park"));
            tupleList.Add(new Tuple<string, string>("Stonebridge Park", "Harlesden"));
            tupleList.Add(new Tuple<string, string>("Paddington", "Edgware Road (Bakerloo)"));
            tupleList.Add(new Tuple<string, string>("Harlesden", "Willesden Junction"));
            tupleList.Add(new Tuple<string, string>("Willesden Junction", "Kensal Green"));
            tupleList.Add(new Tuple<string, string>("Kensal Green", "Queens Park"));
            tupleList.Add(new Tuple<string, string>("Queens Park", "Kilburn Park"));
            tupleList.Add(new Tuple<string, string>("East Acton", "North Acton"));
            tupleList.Add(new Tuple<string, string>("North Acton", "West Acton"));
            tupleList.Add(new Tuple<string, string>("West Acton", "Ealing Broadway"));
            tupleList.Add(new Tuple<string, string>("North Acton", "Hanger Lane"));
            tupleList.Add(new Tuple<string, string>("Hanger Lane", "Perivale"));
            tupleList.Add(new Tuple<string, string>("Perivale", "Greenford"));
            tupleList.Add(new Tuple<string, string>("Greenford", "Northolt"));
            tupleList.Add(new Tuple<string, string>("Northolt", "South Ruislip"));
            tupleList.Add(new Tuple<string, string>("South Ruislip", "Ruislip Gardens"));
            tupleList.Add(new Tuple<string, string>("Ruislip Gardens", "West Ruislip"));
            tupleList.Add(new Tuple<string, string>("Wanstead", "Redbridge"));
            tupleList.Add(new Tuple<string, string>("White City", "East Acton"));
            tupleList.Add(new Tuple<string, string>("Shepherds Bush", "White City"));
            tupleList.Add(new Tuple<string, string>("Holland Park", "Shepherds Bush"));
            tupleList.Add(new Tuple<string, string>("Grange Hill", "Chigwell"));
            tupleList.Add(new Tuple<string, string>("Hainault", "Grange Hill"));
            tupleList.Add(new Tuple<string, string>("Fairlop", "Hainault"));
            tupleList.Add(new Tuple<string, string>("Barkingside", "Fairlop"));
            tupleList.Add(new Tuple<string, string>("Newbury Park", "Barkingside"));
            tupleList.Add(new Tuple<string, string>("Gants Hill", "Newbury Park"));
            tupleList.Add(new Tuple<string, string>("Redbridge", "Gants Hill"));
            tupleList.Add(new Tuple<string, string>("Leytonstone", "Wanstead"));
            tupleList.Add(new Tuple<string, string>("Snaresbrook", "Leytonstone"));
            tupleList.Add(new Tuple<string, string>("South Woodford", "Snaresbrook"));
            tupleList.Add(new Tuple<string, string>("Woodford", "South Woodford"));
            tupleList.Add(new Tuple<string, string>("Buckhurst Hill", "Woodford"));
            tupleList.Add(new Tuple<string, string>("Loughton", "Buckhurst Hill"));
            tupleList.Add(new Tuple<string, string>("Debden", "Loughton"));
            tupleList.Add(new Tuple<string, string>("Theydon Bois", "Debden"));
            tupleList.Add(new Tuple<string, string>("Chigwell", "Roding Valley"));
            tupleList.Add(new Tuple<string, string>("Leytonstone", "Leyton"));
            tupleList.Add(new Tuple<string, string>("Leyton", "Stratford"));
            tupleList.Add(new Tuple<string, string>("Notting Hill Gate", "Holland Park"));
            tupleList.Add(new Tuple<string, string>("Queensway", "Notting Hill Gate"));
            tupleList.Add(new Tuple<string, string>("Lancaster Gate", "Queensway"));
            tupleList.Add(new Tuple<string, string>("Marble Arch", "Lancaster Gate"));
            tupleList.Add(new Tuple<string, string>("Bond Street", "Marble Arch"));
            tupleList.Add(new Tuple<string, string>("Oxford Circus", "Bond Street"));
            tupleList.Add(new Tuple<string, string>("Tottenham Court Road", "Oxford Circus"));
            tupleList.Add(new Tuple<string, string>("Holborn", "Tottenham Court Road"));
            tupleList.Add(new Tuple<string, string>("Chancery Lane", "Holborn"));
            tupleList.Add(new Tuple<string, string>("St. Pauls", "Chancery Lane"));
            tupleList.Add(new Tuple<string, string>("Bank", "St. Pauls"));
            tupleList.Add(new Tuple<string, string>("Liverpool Street", "Bank"));
            tupleList.Add(new Tuple<string, string>("Bethnal Green", "Liverpool Street"));
            tupleList.Add(new Tuple<string, string>("Mile End", "Bethnal Green"));
            tupleList.Add(new Tuple<string, string>("Stratford", "Mile End"));
            tupleList.Add(new Tuple<string, string>("Epping", "Theydon Bois"));
            tupleList.Add(new Tuple<string, string>("St. James's Park", "Victoria"));
            tupleList.Add(new Tuple<string, string>("Westminster", "St. James's Park"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Farringdon"));
            tupleList.Add(new Tuple<string, string>("Euston Square", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Great Portland Street", "Euston Square"));
            tupleList.Add(new Tuple<string, string>("Baker Street", "Great Portland Street"));
            tupleList.Add(new Tuple<string, string>("Edgware Road (Circle/District/Hammersmith and City)", "Baker Street"));
            tupleList.Add(new Tuple<string, string>("Cannon Street", "Mansion House"));
            tupleList.Add(new Tuple<string, string>("Mansion House", "Blackfriars"));
            tupleList.Add(new Tuple<string, string>("Gloucester Road", "High Street Kensington"));
            tupleList.Add(new Tuple<string, string>("High Street Kensington", "Notting Hill Gate"));
            tupleList.Add(new Tuple<string, string>("Farringdon", "Barbican"));
            tupleList.Add(new Tuple<string, string>("Barbican", "Moorgate"));
            tupleList.Add(new Tuple<string, string>("Moorgate", "Liverpool Street"));
            tupleList.Add(new Tuple<string, string>("Victoria", "Sloane Square"));
            tupleList.Add(new Tuple<string, string>("Sloane Square", "South Kensington"));
            tupleList.Add(new Tuple<string, string>("South Kensington", "Gloucester Road"));
            tupleList.Add(new Tuple<string, string>("Embankment", "Westminster"));
            tupleList.Add(new Tuple<string, string>("Temple", "Embankment"));
            tupleList.Add(new Tuple<string, string>("Blackfriars", "Temple"));
            tupleList.Add(new Tuple<string, string>("Tower Hill", "Monument"));
            tupleList.Add(new Tuple<string, string>("Aldgate", "Tower Hill"));
            tupleList.Add(new Tuple<string, string>("Liverpool Street", "Aldgate"));
            tupleList.Add(new Tuple<string, string>("Notting Hill Gate", "Bayswater"));
            tupleList.Add(new Tuple<string, string>("Bayswater", "Paddington"));
            tupleList.Add(new Tuple<string, string>("Westbourne Park", "Royal Oak"));
            tupleList.Add(new Tuple<string, string>("Monument", "Cannon Street"));
            tupleList.Add(new Tuple<string, string>("Ladbroke Grove", "Westbourne Park"));
            tupleList.Add(new Tuple<string, string>("Latimer Road", "Ladbroke Grove"));
            tupleList.Add(new Tuple<string, string>("Wood Lane", "Latimer Road"));
            tupleList.Add(new Tuple<string, string>("Shepherds Bush Market", "Wood Lane"));
            tupleList.Add(new Tuple<string, string>("Goldhawk Road", "Shepherds Bush Market"));
            tupleList.Add(new Tuple<string, string>("Royal Oak", "Paddington"));
            tupleList.Add(new Tuple<string, string>("Hammersmith (Met.)", "Goldhawk Road"));
            tupleList.Add(new Tuple<string, string>("Paddington", "Edgware Road (Circle/District/Hammersmith and City)"));
            tupleList.Add(new Tuple<string, string>("Ealing Common", "Ealing Broadway"));
            tupleList.Add(new Tuple<string, string>("Parsons Green", "Putney Bridge"));
            tupleList.Add(new Tuple<string, string>("Fulham Broadway", "Parsons Green"));
            tupleList.Add(new Tuple<string, string>("West Brompton", "Fulham Broadway"));
            tupleList.Add(new Tuple<string, string>("Earls Court", "West Brompton"));
            tupleList.Add(new Tuple<string, string>("Earls Court", "Kensington (Olympia)"));
            tupleList.Add(new Tuple<string, string>("Paddington", "Edgware Road (Circle/District/Hammersmith and City)"));
            tupleList.Add(new Tuple<string, string>("Bayswater", "Paddington"));
            tupleList.Add(new Tuple<string, string>("Notting Hill Gate", "Bayswater"));
            tupleList.Add(new Tuple<string, string>("High Street Kensington", "Notting Hill Gate"));
            tupleList.Add(new Tuple<string, string>("Earls Court", "High Street Kensington"));
            tupleList.Add(new Tuple<string, string>("Gloucester Road", "Earls Court"));
            tupleList.Add(new Tuple<string, string>("South Kensington", "Gloucester Road"));
            tupleList.Add(new Tuple<string, string>("Sloane Square", "South Kensington"));
            tupleList.Add(new Tuple<string, string>("Putney Bridge", "East Putney"));
            tupleList.Add(new Tuple<string, string>("East Putney", "Southfields"));
            tupleList.Add(new Tuple<string, string>("Acton Town", "Ealing Common"));
            tupleList.Add(new Tuple<string, string>("Chiswick Park", "Acton Town"));
            tupleList.Add(new Tuple<string, string>("Kew Gardens", "Richmond"));
            tupleList.Add(new Tuple<string, string>("Gunnersbury", "Kew Gardens"));
            tupleList.Add(new Tuple<string, string>("Turnham Green", "Gunnersbury"));
            tupleList.Add(new Tuple<string, string>("Stamford Brook", "Turnham Green"));
            tupleList.Add(new Tuple<string, string>("Ravenscourt Park", "Stamford Brook"));
            tupleList.Add(new Tuple<string, string>("Hammersmith (District)", "Ravenscourt Park"));
            tupleList.Add(new Tuple<string, string>("Barons Court", "Hammersmith (District)"));
            tupleList.Add(new Tuple<string, string>("West Kensington", "Barons Court"));
            tupleList.Add(new Tuple<string, string>("Earls Court", "West Kensington"));
            tupleList.Add(new Tuple<string, string>("Wimbledon Park", "Wimbledon"));
            tupleList.Add(new Tuple<string, string>("Southfields", "Wimbledon Park"));
            tupleList.Add(new Tuple<string, string>("Victoria", "Sloane Square"));
            tupleList.Add(new Tuple<string, string>("St. James's Park", "Victoria"));
            tupleList.Add(new Tuple<string, string>("Westminster", "St. James's Park"));
            tupleList.Add(new Tuple<string, string>("Upton Park", "Plaistow"));
            tupleList.Add(new Tuple<string, string>("East Ham", "Upton Park"));
            tupleList.Add(new Tuple<string, string>("Barking", "East Ham"));
            tupleList.Add(new Tuple<string, string>("Upney", "Barking"));
            tupleList.Add(new Tuple<string, string>("Becontree", "Upney"));
            tupleList.Add(new Tuple<string, string>("Dagenham Heathway", "Becontree"));
            tupleList.Add(new Tuple<string, string>("Dagenham East", "Dagenham Heathway"));
            tupleList.Add(new Tuple<string, string>("Elm Park", "Dagenham East"));
            tupleList.Add(new Tuple<string, string>("Hornchurch", "Elm Park"));
            tupleList.Add(new Tuple<string, string>("Upminster Bridge", "Hornchurch"));
            tupleList.Add(new Tuple<string, string>("Upminster", "Upminster Bridge"));
            tupleList.Add(new Tuple<string, string>("Turnham Green", "Chiswick Park"));
            tupleList.Add(new Tuple<string, string>("Plaistow", "West Ham"));
            tupleList.Add(new Tuple<string, string>("West Ham", "Bromley-by-Bow"));
            tupleList.Add(new Tuple<string, string>("Bromley-by-Bow", "Bow Road"));
            tupleList.Add(new Tuple<string, string>("Embankment", "Westminster"));
            tupleList.Add(new Tuple<string, string>("Temple", "Embankment"));
            tupleList.Add(new Tuple<string, string>("Blackfriars", "Temple"));
            tupleList.Add(new Tuple<string, string>("Mansion House", "Blackfriars"));
            tupleList.Add(new Tuple<string, string>("Cannon Street", "Mansion House"));
            tupleList.Add(new Tuple<string, string>("Monument", "Cannon Street"));
            tupleList.Add(new Tuple<string, string>("Tower Hill", "Monument"));
            tupleList.Add(new Tuple<string, string>("Aldgate East", "Tower Hill"));
            tupleList.Add(new Tuple<string, string>("Whitechapel", "Aldgate East"));
            tupleList.Add(new Tuple<string, string>("Stepney Green", "Whitechapel"));
            tupleList.Add(new Tuple<string, string>("Bow Church", "Stepney Green"));
            tupleList.Add(new Tuple<string, string>("Bow Road", "Bow Church"));
            tupleList.Add(new Tuple<string, string>("London City Airport", "King George V"));
            tupleList.Add(new Tuple<string, string>("King George V", "Woolwich Arsenal"));
            tupleList.Add(new Tuple<string, string>("Pontoon Dock", "London City Airport"));
            tupleList.Add(new Tuple<string, string>("Cyprus", "Gallions Reach"));
            tupleList.Add(new Tuple<string, string>("Gallions Reach", "Beckton"));
            tupleList.Add(new Tuple<string, string>("Stratford", "Stratford High Street"));
            tupleList.Add(new Tuple<string, string>("Devons Road", "Langdon Park"));
            tupleList.Add(new Tuple<string, string>("Blackwall", "East India"));
            tupleList.Add(new Tuple<string, string>("Abbey Road", "West Ham"));
            tupleList.Add(new Tuple<string, string>("West Ham", "Star Lane"));
            tupleList.Add(new Tuple<string, string>("Star Lane", "Canning Town"));
            tupleList.Add(new Tuple<string, string>("Canning Town", "West Silvertown"));
            tupleList.Add(new Tuple<string, string>("West Silvertown", "Pontoon Dock"));
            tupleList.Add(new Tuple<string, string>("Custom House", "Prince Regent"));
            tupleList.Add(new Tuple<string, string>("Beckton Park", "Cyprus"));
            tupleList.Add(new Tuple<string, string>("Royal Albert", "Beckton Park"));
            tupleList.Add(new Tuple<string, string>("Elverson Road", "Lewisham"));
            tupleList.Add(new Tuple<string, string>("Deptford Bridge", "Elverson Road"));
            tupleList.Add(new Tuple<string, string>("Greenwich", "Deptford Bridge"));
            tupleList.Add(new Tuple<string, string>("Shadwell", "Bank"));
            tupleList.Add(new Tuple<string, string>("Island Gardens", "Cutty Sark for Maritime Greenwich"));
            tupleList.Add(new Tuple<string, string>("Mudchute", "Island Gardens"));
            tupleList.Add(new Tuple<string, string>("Crossharbour and London Arena", "Mudchute"));
            tupleList.Add(new Tuple<string, string>("East India", "Canning Town"));
            tupleList.Add(new Tuple<string, string>("Canning Town", "Royal Victoria"));
            tupleList.Add(new Tuple<string, string>("Royal Victoria", "Custom House"));
            tupleList.Add(new Tuple<string, string>("Prince Regent", "Royal Albert"));
            tupleList.Add(new Tuple<string, string>("Stratford High Street", "Abbey Road"));
            tupleList.Add(new Tuple<string, string>("Poplar", "Blackwall"));
            tupleList.Add(new Tuple<string, string>("Cutty Sark for Maritime Greenwich", "Greenwich"));
            tupleList.Add(new Tuple<string, string>("South Quay", "Crossharbour and London Arena"));
            tupleList.Add(new Tuple<string, string>("Heron Quays", "South Quay"));
            tupleList.Add(new Tuple<string, string>("Canary Wharf", "Heron Quays"));
            tupleList.Add(new Tuple<string, string>("West India Quay", "Canary Wharf"));
            tupleList.Add(new Tuple<string, string>("Poplar", "West India Quay"));
            tupleList.Add(new Tuple<string, string>("Shadwell", "Tower Gateway"));
            tupleList.Add(new Tuple<string, string>("Westferry", "Limehouse"));
            tupleList.Add(new Tuple<string, string>("Poplar", "Westferry"));
            tupleList.Add(new Tuple<string, string>("All Saints", "Poplar"));
            tupleList.Add(new Tuple<string, string>("Stratford International", "Stratford"));
            tupleList.Add(new Tuple<string, string>("Stratford", "Pudding Mill Lane"));
            tupleList.Add(new Tuple<string, string>("Pudding Mill Lane", "Bow Church"));
            tupleList.Add(new Tuple<string, string>("Bow Church", "Devons Road"));
            tupleList.Add(new Tuple<string, string>("Limehouse", "Shadwell"));
            tupleList.Add(new Tuple<string, string>("Langdon Park", "All Saints"));
            tupleList.Add(new Tuple<string, string>("Latimer Road", "Ladbroke Grove"));
            tupleList.Add(new Tuple<string, string>("Wood Lane", "Latimer Road"));
            tupleList.Add(new Tuple<string, string>("Shepherds Bush Market", "Wood Lane"));
            tupleList.Add(new Tuple<string, string>("Goldhawk Road", "Shepherds Bush Market"));
            tupleList.Add(new Tuple<string, string>("Upton Park", "East Ham"));
            tupleList.Add(new Tuple<string, string>("Hammersmith (Met.)", "Goldhawk Road"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Farringdon"));
            tupleList.Add(new Tuple<string, string>("Ladbroke Grove", "Westbourne Park"));
            tupleList.Add(new Tuple<string, string>("Westbourne Park", "Royal Oak"));
            tupleList.Add(new Tuple<string, string>("Royal Oak", "Paddington"));
            tupleList.Add(new Tuple<string, string>("Plaistow", "Upton Park"));
            tupleList.Add(new Tuple<string, string>("West Ham", "Plaistow"));
            tupleList.Add(new Tuple<string, string>("Bromley-by-Bow", "West Ham"));
            tupleList.Add(new Tuple<string, string>("Bow Road", "Bromley-by-Bow"));
            tupleList.Add(new Tuple<string, string>("Mile End", "Bow Road"));
            tupleList.Add(new Tuple<string, string>("Stepney Green", "Mile End"));
            tupleList.Add(new Tuple<string, string>("Whitechapel", "Stepney Green"));
            tupleList.Add(new Tuple<string, string>("Aldgate East", "Whitechapel"));
            tupleList.Add(new Tuple<string, string>("Liverpool Street", "Aldgate East"));
            tupleList.Add(new Tuple<string, string>("Moorgate", "Liverpool Street"));
            tupleList.Add(new Tuple<string, string>("Barbican", "Moorgate"));
            tupleList.Add(new Tuple<string, string>("Farringdon", "Barbican"));
            tupleList.Add(new Tuple<string, string>("Euston Square", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Great Portland Street", "Euston Square"));
            tupleList.Add(new Tuple<string, string>("Baker Street", "Great Portland Street"));
            tupleList.Add(new Tuple<string, string>("Edgware Road (Circle/District/Hammersmith and City)", "Baker Street"));
            tupleList.Add(new Tuple<string, string>("Paddington", "Edgware Road (Circle/District/Hammersmith and City)"));
            tupleList.Add(new Tuple<string, string>("East Ham", "Barking"));
            tupleList.Add(new Tuple<string, string>("Queensbury", "Kingsbury"));
            tupleList.Add(new Tuple<string, string>("Westminster", "Waterloo"));
            tupleList.Add(new Tuple<string, string>("Southwark", "London Bridge"));
            tupleList.Add(new Tuple<string, string>("London Bridge", "Bermondsey"));
            tupleList.Add(new Tuple<string, string>("Bermondsey", "Canada Water"));
            tupleList.Add(new Tuple<string, string>("Canada Water", "Canary Wharf"));
            tupleList.Add(new Tuple<string, string>("Canary Wharf", "North Greenwich"));
            tupleList.Add(new Tuple<string, string>("North Greenwich", "Canning Town"));
            tupleList.Add(new Tuple<string, string>("Canning Town", "West Ham"));
            tupleList.Add(new Tuple<string, string>("West Ham", "Stratford"));
            tupleList.Add(new Tuple<string, string>("Canons Park", "Queensbury"));
            tupleList.Add(new Tuple<string, string>("Stanmore", "Canons Park"));
            tupleList.Add(new Tuple<string, string>("Waterloo", "Southwark"));
            tupleList.Add(new Tuple<string, string>("Green Park", "Westminster"));
            tupleList.Add(new Tuple<string, string>("Bond Street", "Green Park"));
            tupleList.Add(new Tuple<string, string>("Kingsbury", "Wembley Park"));
            tupleList.Add(new Tuple<string, string>("Wembley Park", "Neasden"));
            tupleList.Add(new Tuple<string, string>("Neasden", "Dollis Hill"));
            tupleList.Add(new Tuple<string, string>("Dollis Hill", "Willesden Green"));
            tupleList.Add(new Tuple<string, string>("Willesden Green", "Kilburn"));
            tupleList.Add(new Tuple<string, string>("Kilburn", "West Hampstead"));
            tupleList.Add(new Tuple<string, string>("West Hampstead", "Finchley Road"));
            tupleList.Add(new Tuple<string, string>("Finchley Road", "Swiss Cottage"));
            tupleList.Add(new Tuple<string, string>("Swiss Cottage", "St. Johns Wood"));
            tupleList.Add(new Tuple<string, string>("St. Johns Wood", "Baker Street"));
            tupleList.Add(new Tuple<string, string>("Baker Street", "Bond Street"));
            tupleList.Add(new Tuple<string, string>("Finchley Road", "Wembley Park"));
            tupleList.Add(new Tuple<string, string>("West Harrow", "Eastcote"));
            tupleList.Add(new Tuple<string, string>("Chalfont and Latimer", "Amersham"));
            tupleList.Add(new Tuple<string, string>("Chorleywood", "Chalfont and Latimer"));
            tupleList.Add(new Tuple<string, string>("Chalfont and Latimer", "Chesham"));
            tupleList.Add(new Tuple<string, string>("Eastcote", "Ruislip Manor"));
            tupleList.Add(new Tuple<string, string>("Ruislip Manor", "Ruislip"));
            tupleList.Add(new Tuple<string, string>("Ruislip", "Ickenham"));
            tupleList.Add(new Tuple<string, string>("Ickenham", "Hillingdon"));
            tupleList.Add(new Tuple<string, string>("Hillingdon", "Uxbridge"));
            tupleList.Add(new Tuple<string, string>("Harrow-on-the-Hill", "North Harrow"));
            tupleList.Add(new Tuple<string, string>("North Harrow", "Pinner"));
            tupleList.Add(new Tuple<string, string>("Pinner", "Northwood Hills"));
            tupleList.Add(new Tuple<string, string>("Northwood Hills", "Northwood"));
            tupleList.Add(new Tuple<string, string>("Moor Park", "Croxley"));
            tupleList.Add(new Tuple<string, string>("Moor Park", "Rickmansworth"));
            tupleList.Add(new Tuple<string, string>("Croxley", "Watford"));
            tupleList.Add(new Tuple<string, string>("Harrow-on-the-Hill", "West Harrow"));
            tupleList.Add(new Tuple<string, string>("Northwick Park", "Harrow-on-the-Hill"));
            tupleList.Add(new Tuple<string, string>("Barbican", "Farringdon"));
            tupleList.Add(new Tuple<string, string>("Liverpool Street", "Moorgate"));
            tupleList.Add(new Tuple<string, string>("Moorgate", "Barbican"));
            tupleList.Add(new Tuple<string, string>("Farringdon", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Euston Square"));
            tupleList.Add(new Tuple<string, string>("Euston Square", "Great Portland Street"));
            tupleList.Add(new Tuple<string, string>("Great Portland Street", "Baker Street"));
            tupleList.Add(new Tuple<string, string>("Baker Street", "Finchley Road"));
            tupleList.Add(new Tuple<string, string>("Rickmansworth", "Chorleywood"));
            tupleList.Add(new Tuple<string, string>("Wembley Park", "Preston Road"));
            tupleList.Add(new Tuple<string, string>("Preston Road", "Northwick Park"));
            tupleList.Add(new Tuple<string, string>("Aldgate", "Liverpool Street"));
            tupleList.Add(new Tuple<string, string>("Northwood", "Moor Park"));
            tupleList.Add(new Tuple<string, string>("Hendon Central", "Colindale"));
            tupleList.Add(new Tuple<string, string>("Brent Cross", "Hendon Central"));
            tupleList.Add(new Tuple<string, string>("Golders Green", "Brent Cross"));
            tupleList.Add(new Tuple<string, string>("Hampstead", "Golders Green"));
            tupleList.Add(new Tuple<string, string>("Belsize Park", "Hampstead"));
            tupleList.Add(new Tuple<string, string>("Chalk Farm", "Belsize Park"));
            tupleList.Add(new Tuple<string, string>("Camden Town", "Chalk Farm"));
            tupleList.Add(new Tuple<string, string>("Euston", "Camden Town"));
            tupleList.Add(new Tuple<string, string>("Mornington Crescent", "Camden Town"));
            tupleList.Add(new Tuple<string, string>("Euston", "Mornington Crescent"));
            tupleList.Add(new Tuple<string, string>("Warren Street", "Euston"));
            tupleList.Add(new Tuple<string, string>("Colindale", "Burnt Oak"));
            tupleList.Add(new Tuple<string, string>("Burnt Oak", "Edgware"));
            tupleList.Add(new Tuple<string, string>("Totteridge and Whetstone", "High Barnet"));
            tupleList.Add(new Tuple<string, string>("Woodside Park", "Totteridge and Whetstone"));
            tupleList.Add(new Tuple<string, string>("West Finchley", "Woodside Park"));
            tupleList.Add(new Tuple<string, string>("Finchley Central", "West Finchley"));
            tupleList.Add(new Tuple<string, string>("East Finchley", "Finchley Central"));
            tupleList.Add(new Tuple<string, string>("East Finchley", "Mill Hill East"));
            tupleList.Add(new Tuple<string, string>("Highgate", "East Finchley"));
            tupleList.Add(new Tuple<string, string>("Archway", "Highgate"));
            tupleList.Add(new Tuple<string, string>("Tufnell Park", "Archway"));
            tupleList.Add(new Tuple<string, string>("Kentish Town", "Tufnell Park"));
            tupleList.Add(new Tuple<string, string>("Camden Town", "Kentish Town"));
            tupleList.Add(new Tuple<string, string>("Goodge Street", "Warren Street"));
            tupleList.Add(new Tuple<string, string>("Morden", "South Wimbledon"));
            tupleList.Add(new Tuple<string, string>("Kennington", "Elephant and Castle"));
            tupleList.Add(new Tuple<string, string>("Oval", "Kennington"));
            tupleList.Add(new Tuple<string, string>("Stockwell", "Oval"));
            tupleList.Add(new Tuple<string, string>("Clapham North", "Stockwell"));
            tupleList.Add(new Tuple<string, string>("Clapham Common", "Clapham North"));
            tupleList.Add(new Tuple<string, string>("Clapham South", "Clapham Common"));
            tupleList.Add(new Tuple<string, string>("Balham", "Clapham South"));
            tupleList.Add(new Tuple<string, string>("Tooting Bec", "Balham"));
            tupleList.Add(new Tuple<string, string>("Tooting Broadway", "Tooting Bec"));
            tupleList.Add(new Tuple<string, string>("Colliers Wood", "Tooting Broadway"));
            tupleList.Add(new Tuple<string, string>("South Wimbledon", "Colliers Wood"));
            tupleList.Add(new Tuple<string, string>("Elephant and Castle", "Borough"));
            tupleList.Add(new Tuple<string, string>("Borough", "London Bridge"));
            tupleList.Add(new Tuple<string, string>("Tottenham Court Road", "Goodge Street"));
            tupleList.Add(new Tuple<string, string>("Leicester Square", "Tottenham Court Road"));
            tupleList.Add(new Tuple<string, string>("Charing Cross", "Leicester Square"));
            tupleList.Add(new Tuple<string, string>("Embankment", "Charing Cross"));
            tupleList.Add(new Tuple<string, string>("Waterloo", "Embankment"));
            tupleList.Add(new Tuple<string, string>("Kennington", "Waterloo"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Euston"));
            tupleList.Add(new Tuple<string, string>("London Bridge", "Bank"));
            tupleList.Add(new Tuple<string, string>("Bank", "Moorgate"));
            tupleList.Add(new Tuple<string, string>("Moorgate", "Old Street"));
            tupleList.Add(new Tuple<string, string>("Old Street", "Angel"));
            tupleList.Add(new Tuple<string, string>("Angel", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Wanstead Park", "Woodgrange Park"));
            tupleList.Add(new Tuple<string, string>("Woodgrange Park", "Barking"));
            tupleList.Add(new Tuple<string, string>("Highbury and Islington", "Canonbury"));
            tupleList.Add(new Tuple<string, string>("Canonbury", "Dalston Junction"));
            tupleList.Add(new Tuple<string, string>("Dalston Junction", "Haggerston"));
            tupleList.Add(new Tuple<string, string>("Haggerston", "Hoxton"));
            tupleList.Add(new Tuple<string, string>("Hoxton", "Shoreditch High Street"));
            tupleList.Add(new Tuple<string, string>("Shoreditch High Street", "Whitechapel"));
            tupleList.Add(new Tuple<string, string>("Leytonstone High Road", "Wanstead Park"));
            tupleList.Add(new Tuple<string, string>("Leyton Midland Road", "Leytonstone High Road"));
            tupleList.Add(new Tuple<string, string>("Walthamstow Queens Road", "Leyton Midland Road"));
            tupleList.Add(new Tuple<string, string>("West Brompton", "Imperial Wharf"));
            tupleList.Add(new Tuple<string, string>("Imperial Wharf", "Clapham Junction"));
            tupleList.Add(new Tuple<string, string>("Gospel Oak", "Upper Holloway"));
            tupleList.Add(new Tuple<string, string>("Upper Holloway", "Crouch Hill"));
            tupleList.Add(new Tuple<string, string>("Crouch Hill", "Harringay Green Lanes"));
            tupleList.Add(new Tuple<string, string>("Harringay Green Lanes", "South Tottenham"));
            tupleList.Add(new Tuple<string, string>("South Tottenham", "Blackhorse Road"));
            tupleList.Add(new Tuple<string, string>("Blackhorse Road", "Walthamstow Queens Road"));
            tupleList.Add(new Tuple<string, string>("Whitechapel", "Shadwell"));
            tupleList.Add(new Tuple<string, string>("Shadwell", "Wapping"));
            tupleList.Add(new Tuple<string, string>("Wapping", "Rotherhithe"));
            tupleList.Add(new Tuple<string, string>("Anerley", "Norwood Junction"));
            tupleList.Add(new Tuple<string, string>("Norwood Junction", "West Croydon"));
            tupleList.Add(new Tuple<string, string>("Sydenham", "Crystal Palace"));
            tupleList.Add(new Tuple<string, string>("Surrey Quays", "Queens Road Peckham"));
            tupleList.Add(new Tuple<string, string>("Queens Road Peckham", "Peckham Rye"));
            tupleList.Add(new Tuple<string, string>("Peckham Rye", "Denmark Hill"));
            tupleList.Add(new Tuple<string, string>("Denmark Hill", "Clapham High Street"));
            tupleList.Add(new Tuple<string, string>("Clapham High Street", "Wandsworth Road"));
            tupleList.Add(new Tuple<string, string>("Penge West", "Anerley"));
            tupleList.Add(new Tuple<string, string>("Sydenham", "Penge West"));
            tupleList.Add(new Tuple<string, string>("Rotherhithe", "Canada Water"));
            tupleList.Add(new Tuple<string, string>("Canada Water", "Surrey Quays"));
            tupleList.Add(new Tuple<string, string>("Surrey Quays", "New Cross"));
            tupleList.Add(new Tuple<string, string>("Surrey Quays", "New Cross Gate"));
            tupleList.Add(new Tuple<string, string>("New Cross Gate", "Brockley"));
            tupleList.Add(new Tuple<string, string>("Brockley", "Honor Oak Park"));
            tupleList.Add(new Tuple<string, string>("Honor Oak Park", "Forest Hill"));
            tupleList.Add(new Tuple<string, string>("Forest Hill", "Sydenham"));
            tupleList.Add(new Tuple<string, string>("Wandsworth Road", "Clapham Junction"));
            tupleList.Add(new Tuple<string, string>("Watford Junction", "Watford High Street"));
            tupleList.Add(new Tuple<string, string>("Harlesden", "Willesden Junction"));
            tupleList.Add(new Tuple<string, string>("Willesden Junction", "Kensal Green"));
            tupleList.Add(new Tuple<string, string>("Kensal Green", "Queens Park"));
            tupleList.Add(new Tuple<string, string>("Queens Park", "Kilburn High Road"));
            tupleList.Add(new Tuple<string, string>("Kilburn High Road", "South Hampstead"));
            tupleList.Add(new Tuple<string, string>("South Hampstead", "Euston"));
            tupleList.Add(new Tuple<string, string>("Richmond", "Kew Gardens"));
            tupleList.Add(new Tuple<string, string>("Kew Gardens", "Gunnersbury"));
            tupleList.Add(new Tuple<string, string>("Stonebridge Park", "Harlesden"));
            tupleList.Add(new Tuple<string, string>("Wembley Central", "Stonebridge Park"));
            tupleList.Add(new Tuple<string, string>("North Wembley", "Wembley Central"));
            tupleList.Add(new Tuple<string, string>("Watford High Street", "Bushey"));
            tupleList.Add(new Tuple<string, string>("Bushey", "Carpenders Park"));
            tupleList.Add(new Tuple<string, string>("Carpenders Park", "Hatch End"));
            tupleList.Add(new Tuple<string, string>("Hatch End", "Headstone Lane"));
            tupleList.Add(new Tuple<string, string>("Headstone Lane", "Harrow and Wealdstone"));
            tupleList.Add(new Tuple<string, string>("Harrow and Wealdstone", "Kenton"));
            tupleList.Add(new Tuple<string, string>("Kenton", "South Kenton"));
            tupleList.Add(new Tuple<string, string>("South Kenton", "North Wembley"));
            tupleList.Add(new Tuple<string, string>("Gunnersbury", "South Acton"));
            tupleList.Add(new Tuple<string, string>("South Acton", "Acton Central"));
            tupleList.Add(new Tuple<string, string>("Caledonian Road and Barnsbury", "Highbury and Islington"));
            tupleList.Add(new Tuple<string, string>("Canonbury", "Dalston Kingsland"));
            tupleList.Add(new Tuple<string, string>("Dalston Kingsland", "Hackney Central"));
            tupleList.Add(new Tuple<string, string>("Hackney Central", "Homerton"));
            tupleList.Add(new Tuple<string, string>("Homerton", "Hackney Wick"));
            tupleList.Add(new Tuple<string, string>("Hackney Wick", "Stratford"));
            tupleList.Add(new Tuple<string, string>("Willesden Junction", "Shepherds Bush"));
            tupleList.Add(new Tuple<string, string>("Shepherds Bush", "Kensington (Olympia)"));
            tupleList.Add(new Tuple<string, string>("Camden Road", "Caledonian Road and Barnsbury"));
            tupleList.Add(new Tuple<string, string>("Kentish Town West", "Camden Road"));
            tupleList.Add(new Tuple<string, string>("Gospel Oak", "Kentish Town West"));
            tupleList.Add(new Tuple<string, string>("Acton Central", "Willesden Junction"));
            tupleList.Add(new Tuple<string, string>("Willesden Junction", "Kensal Rise"));
            tupleList.Add(new Tuple<string, string>("Kensal Rise", "Brondesbury Park"));
            tupleList.Add(new Tuple<string, string>("Brondesbury Park", "Brondesbury"));
            tupleList.Add(new Tuple<string, string>("Brondesbury", "West Hampstead"));
            tupleList.Add(new Tuple<string, string>("West Hampstead", "Finchley Road and Frognal"));
            tupleList.Add(new Tuple<string, string>("Finchley Road and Frognal", "Hampstead Heath"));
            tupleList.Add(new Tuple<string, string>("Hampstead Heath", "Gospel Oak"));
            tupleList.Add(new Tuple<string, string>("Kensington (Olympia)", "West Brompton"));
            tupleList.Add(new Tuple<string, string>("South Harrow", "Sudbury Hill"));
            tupleList.Add(new Tuple<string, string>("South Harrow", "Rayners Lane"));
            tupleList.Add(new Tuple<string, string>("Turnpike Lane", "Manor House"));
            tupleList.Add(new Tuple<string, string>("Manor House", "Finsbury Park"));
            tupleList.Add(new Tuple<string, string>("Finsbury Park", "Arsenal"));
            tupleList.Add(new Tuple<string, string>("Knightsbridge", "South Kensington"));
            tupleList.Add(new Tuple<string, string>("Arsenal", "Holloway Road"));
            tupleList.Add(new Tuple<string, string>("Wood Green", "Turnpike Lane"));
            tupleList.Add(new Tuple<string, string>("Bounds Green", "Wood Green"));
            tupleList.Add(new Tuple<string, string>("Arnos Grove", "Bounds Green"));
            tupleList.Add(new Tuple<string, string>("Southgate", "Arnos Grove"));
            tupleList.Add(new Tuple<string, string>("Oakwood", "Southgate"));
            tupleList.Add(new Tuple<string, string>("Cockfosters", "Oakwood"));
            tupleList.Add(new Tuple<string, string>("Earls Court", "Barons Court"));
            tupleList.Add(new Tuple<string, string>("Holloway Road", "Caledonian Road"));
            tupleList.Add(new Tuple<string, string>("Caledonian Road", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Hillingdon", "Uxbridge"));
            tupleList.Add(new Tuple<string, string>("Hatton Cross", "Heathrow Terminal 4"));
            tupleList.Add(new Tuple<string, string>("Hatton Cross", "Heathrow Terminals 1 2 3"));
            tupleList.Add(new Tuple<string, string>("Hounslow West", "Hatton Cross"));
            tupleList.Add(new Tuple<string, string>("Hounslow Central", "Hounslow West"));
            tupleList.Add(new Tuple<string, string>("Osterley", "Hounslow East"));
            tupleList.Add(new Tuple<string, string>("Boston Manor", "Osterley"));
            tupleList.Add(new Tuple<string, string>("Northfields", "Boston Manor"));
            tupleList.Add(new Tuple<string, string>("South Ealing", "Northfields"));
            tupleList.Add(new Tuple<string, string>("Acton Town", "South Ealing"));
            tupleList.Add(new Tuple<string, string>("Heathrow Terminals 1 2 3", "Heathrow Terminal 4"));
            tupleList.Add(new Tuple<string, string>("Heathrow Terminals 1 2 3", "Heathrow Terminal 5"));
            tupleList.Add(new Tuple<string, string>("Acton Town", "Ealing Common"));
            tupleList.Add(new Tuple<string, string>("Ickenham", "Hillingdon"));
            tupleList.Add(new Tuple<string, string>("Ruislip", "Ickenham"));
            tupleList.Add(new Tuple<string, string>("Ruislip Manor", "Ruislip"));
            tupleList.Add(new Tuple<string, string>("Eastcote", "Ruislip Manor"));
            tupleList.Add(new Tuple<string, string>("Sudbury Town", "Sudbury Hill"));
            tupleList.Add(new Tuple<string, string>("Alperton", "Sudbury Town"));
            tupleList.Add(new Tuple<string, string>("Park Royal", "Alperton"));
            tupleList.Add(new Tuple<string, string>("North Ealing", "Park Royal"));
            tupleList.Add(new Tuple<string, string>("Ealing Common", "North Ealing"));
            tupleList.Add(new Tuple<string, string>("Rayners Lane", "Eastcote"));
            tupleList.Add(new Tuple<string, string>("Barons Court", "Hammersmith (District)"));
            tupleList.Add(new Tuple<string, string>("Hammersmith (District)", "Turnham Green"));
            tupleList.Add(new Tuple<string, string>("Hyde Park Corner", "Knightsbridge"));
            tupleList.Add(new Tuple<string, string>("Green Park", "Hyde Park Corner"));
            tupleList.Add(new Tuple<string, string>("Piccadilly Circus", "Green Park"));
            tupleList.Add(new Tuple<string, string>("Gloucester Road", "Earls Court"));
            tupleList.Add(new Tuple<string, string>("Leicester Square", "Piccadilly Circus"));
            tupleList.Add(new Tuple<string, string>("Covent Garden", "Leicester Square"));
            tupleList.Add(new Tuple<string, string>("Hounslow East", "Hounslow Central"));
            tupleList.Add(new Tuple<string, string>("Turnham Green", "Acton Town"));
            tupleList.Add(new Tuple<string, string>("Holborn", "Covent Garden"));
            tupleList.Add(new Tuple<string, string>("Russell Square", "Holborn"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Russell Square"));
            tupleList.Add(new Tuple<string, string>("South Kensington", "Gloucester Road"));
            tupleList.Add(new Tuple<string, string>("Beckenham Road", "Beckenham Junction"));
            tupleList.Add(new Tuple<string, string>("Avenue Road", "Beckenham Road"));
            tupleList.Add(new Tuple<string, string>("Birkbeck", "Avenue Road"));
            tupleList.Add(new Tuple<string, string>("Harrington Road", "Birkbeck"));
            tupleList.Add(new Tuple<string, string>("Arena", "Harrington Road"));
            tupleList.Add(new Tuple<string, string>("Woodside", "Arena"));
            tupleList.Add(new Tuple<string, string>("Blackhorse Lane", "Woodside"));
            tupleList.Add(new Tuple<string, string>("Addiscombe", "Blackhorse Lane"));
            tupleList.Add(new Tuple<string, string>("Arena", "Elmers End"));
            tupleList.Add(new Tuple<string, string>("Sandilands", "Lloyd Park"));
            tupleList.Add(new Tuple<string, string>("George Street", "Church Street"));
            tupleList.Add(new Tuple<string, string>("East Croydon", "George Street"));
            tupleList.Add(new Tuple<string, string>("King Henry's Drive", "New Addington"));
            tupleList.Add(new Tuple<string, string>("Fieldway", "King Henry's Drive"));
            tupleList.Add(new Tuple<string, string>("Addington Village", "Fieldway"));
            tupleList.Add(new Tuple<string, string>("Gravel Hill", "Addington Village"));
            tupleList.Add(new Tuple<string, string>("Coombe Lane", "Gravel Hill"));
            tupleList.Add(new Tuple<string, string>("Lloyd Park", "Coombe Lane"));
            tupleList.Add(new Tuple<string, string>("Sandilands", "Addiscombe"));
            tupleList.Add(new Tuple<string, string>("Lebanon Road", "Sandilands"));
            tupleList.Add(new Tuple<string, string>("Mitcham Junction", "Beddington Lane"));
            tupleList.Add(new Tuple<string, string>("Mitcham", "Mitcham Junction"));
            tupleList.Add(new Tuple<string, string>("Belgrave Walk", "Mitcham"));
            tupleList.Add(new Tuple<string, string>("Phipps Bridge", "Belgrave Walk"));
            tupleList.Add(new Tuple<string, string>("Morden Road", "Phipps Bridge"));
            tupleList.Add(new Tuple<string, string>("Merton Park", "Morden Road"));
            tupleList.Add(new Tuple<string, string>("Dundonald Road", "Merton Park"));
            tupleList.Add(new Tuple<string, string>("Wimbledon", "Dundonald Road"));
            tupleList.Add(new Tuple<string, string>("Beddington Lane", "Therapia Lane"));
            tupleList.Add(new Tuple<string, string>("Therapia Lane", "Ampere Way"));
            tupleList.Add(new Tuple<string, string>("East Croydon", "Lebanon Road"));
            tupleList.Add(new Tuple<string, string>("Wellesley Road", "East Croydon"));
            tupleList.Add(new Tuple<string, string>("West Croydon", "Wellesley Road"));
            tupleList.Add(new Tuple<string, string>("Centrale", "West Croydon"));
            tupleList.Add(new Tuple<string, string>("Reeves Corner", "Centrale"));
            tupleList.Add(new Tuple<string, string>("Wandle Park", "Reeves Corner"));
            tupleList.Add(new Tuple<string, string>("Waddon Marsh", "Wandle Park"));
            tupleList.Add(new Tuple<string, string>("Ampere Way", "Waddon Marsh"));
            tupleList.Add(new Tuple<string, string>("Church Street", "Centrale"));
            tupleList.Add(new Tuple<string, string>("Walthamstow Central", "Blackhorse Road"));
            tupleList.Add(new Tuple<string, string>("Seven Sisters", "Finsbury Park"));
            tupleList.Add(new Tuple<string, string>("Stockwell", "Brixton"));
            tupleList.Add(new Tuple<string, string>("Tottenham Hale", "Seven Sisters"));
            tupleList.Add(new Tuple<string, string>("Blackhorse Road", "Tottenham Hale"));
            tupleList.Add(new Tuple<string, string>("Finsbury Park", "Highbury and Islington"));
            tupleList.Add(new Tuple<string, string>("Warren Street", "Oxford Circus"));
            tupleList.Add(new Tuple<string, string>("Oxford Circus", "Green Park"));
            tupleList.Add(new Tuple<string, string>("Green Park", "Victoria"));
            tupleList.Add(new Tuple<string, string>("Kings Cross St. Pancras", "Warren Street"));
            tupleList.Add(new Tuple<string, string>("Victoria", "Pimlico"));
            tupleList.Add(new Tuple<string, string>("Pimlico", "Vauxhall"));
            tupleList.Add(new Tuple<string, string>("Vauxhall", "Stockwell"));
            tupleList.Add(new Tuple<string, string>("Highbury and Islington", "Kings Cross St. Pancras"));
            tupleList.Add(new Tuple<string, string>("Waterloo", "Bank"));
            return tupleList;
        }
    }
}